version: '3.8'

services:
  mkdocs:
    image: python:3.11-slim
    container_name: kamigami-mkdocs
    working_dir: /docs
    volumes:
      - .:/docs
    ports:
      - "8000:8000"
    command: >
      sh -c "pip install -r requirements.txt && mkdocs serve -a 0.0.0.0:8000"
    environment:
      - PYTHONUNBUFFERED=1