name: CI

# プルリクエストとメインブランチへのプッシュ時に実行
on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  # リント・ビルドチェック
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    
    steps:
    # リポジトリのチェックアウト
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Pythonのセットアップ
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    # 依存関係のインストール
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov flake8
    
    # ビルドテスト
    - name: Build documentation
      run: |
        mkdocs build --strict --verbose
    
    # リンクチェック
    - name: Check links
      run: |
        pip install linkchecker
        mkdocs serve -a 127.0.0.1:8000 &
        sleep 5
        linkchecker http://127.0.0.1:8000 --ignore-url=^mailto: --ignore-url=^https://github.com.* || true
        pkill -f "mkdocs serve"
    
    # ビルド成果物のサイズチェック
    - name: Check build size
      run: |
        du -sh site/
        find site -type f -name "*.html" | wc -l
        find site -type f -name "*.css" | wc -l
        find site -type f -name "*.js" | wc -l